#!/usr/bin/env python3
"""Regenerates claude-box-jail.svg.

The blade geometry is computed rather than hand-typed so the burst stays
symmetric and easy to retune -- run this after changing anything below,
then commit the SVG (that file, not this script, is what ships).
"""
import math

CX = CY = 128.0

# (angle_deg, length, half_width) -- 12 blades on a 30 degree spacing,
# alternating long/short, rotated off-axis so they don't line up with the
# bars in front of them.
# Twelve blades on a 30 degree spacing, alternating long/short and
# rotated off-axis so they don't line up with the bars in front of them.
# Fewer, chunkier blades (8 at 45 degrees, half-widths 15/10) survive a
# 48px dash better but read as a pinwheel rather than Claude's mark --
# the trade is right here only because GNOME draws this at 96px and up.
ROTATION = 15
BLADES = []
for i in range(12):
    long_one = (i % 2 == 0)
    BLADES.append((ROTATION + i * 30,
                   88 if long_one else 64,
                   11.0 if long_one else 7.0))

BAR_X = (56, 100, 144, 188)
BAR_W = 16


def blade_path(angle, length, halfw):
    a = math.radians(angle)
    ux, uy = math.cos(a), -math.sin(a)   # outward unit vector (SVG y grows down)
    px, py = -uy, ux                     # perpendicular
    tip = (CX + ux * length, CY + uy * length)
    mid = (CX + ux * length * 0.36, CY + uy * length * 0.36)
    return (f"M {CX:.1f} {CY:.1f} "
            f"Q {mid[0] + px * halfw:.1f} {mid[1] + py * halfw:.1f} {tip[0]:.1f} {tip[1]:.1f} "
            f"Q {mid[0] - px * halfw:.1f} {mid[1] - py * halfw:.1f} {CX:.1f} {CY:.1f} Z")


blades = "\n    ".join(f'<path d="{blade_path(*b)}"/>' for b in BLADES)
shadows = "\n    ".join(
    f'<rect x="{x + 4}" y="34" width="{BAR_W}" height="188" rx="8" fill="#000000" opacity="0.16"/>'
    for x in BAR_X)
bars = "\n    ".join(
    f'<rect x="{x}" y="34" width="{BAR_W}" height="188" rx="8" fill="url(#steel)"/>\n    '
    f'<rect x="{x + 3.5}" y="40" width="3.5" height="176" rx="1.75" fill="#ffffff" opacity="0.16"/>'
    for x in BAR_X)

# The root element comes FIRST, with no XML declaration and the comment
# moved inside it. gdk-pixbuf picks a loader by sniffing a short window at
# the head of the file, so a header comment pushes "<svg" out of range and
# librsvg reports "couldn't recognize the image file format" -- which in
# practice means GNOME shows no icon at all while Qt, which parses instead
# of sniffing, renders it fine.
SVG = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256">
  <!--
  Alternative app icon: the Claude mark behind bars, which is the joke
  the whole project runs on — a box is a cell you put an agent in.

  Generated by packaging/make-jail-icon.py; edit that, not this. Drawn in
  gui/src/Theme.cpp's palette (window #1b1c1e, border #33353a, accent
  #d97757) so it matches the app it launches.

  The starburst is a stylized homage, not Anthropic's official mark;
  don't pass it off as the real logo.
  -->
  <defs>
    <linearGradient id="steel" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0"    stop-color="#5c626c"/>
      <stop offset="0.35" stop-color="#aab1bc"/>
      <stop offset="0.62" stop-color="#7e838d"/>
      <stop offset="1"    stop-color="#4a4f57"/>
    </linearGradient>
    <radialGradient id="glow" cx="0.5" cy="0.5" r="0.5">
      <stop offset="0" stop-color="#d97757" stop-opacity="0.30"/>
      <stop offset="1" stop-color="#d97757" stop-opacity="0"/>
    </radialGradient>
  </defs>

  <rect x="8" y="8" width="240" height="240" rx="52" fill="#1b1c1e"/>
  <rect x="8.75" y="8.75" width="238.5" height="238.5" rx="51.25" fill="none" stroke="#33353a" stroke-width="1.5"/>

  <!-- the cell behind the prisoner -->
  <rect x="34" y="34" width="188" height="188" rx="24" fill="#101113"/>
  <circle cx="128" cy="128" r="88" fill="url(#glow)"/>

  <!-- the Claude mark -->
  <g fill="#d97757">
    {blades}
  </g>

  <!-- bars: shadows first, so they fall across the mark and not the frame -->
  <g>
    {shadows}
  </g>
  <g>
    {bars}
  </g>

  <!-- top and bottom rails -->
  <rect x="34" y="34" width="188" height="14" rx="7" fill="url(#steel)"/>
  <rect x="34" y="208" width="188" height="14" rx="7" fill="url(#steel)"/>
</svg>
'''

if __name__ == "__main__":
    with open("claude-box-jail.svg", "w") as f:
        f.write(SVG)
    print("wrote claude-box-jail.svg")
